-- Cockpit BLG : verrou partagé de niveau passage (tick).
-- Ce fichier préparé le 23 septembre n'est plus à appliquer : son contenu est repris, à l'identique pour
-- la table et les deux fonctions, par la migration numérotée supabase/migrations/017_cockpit_tick_lease.sql
-- (rejouable, inscrite dans cockpit_migrations). Le code du tick l'appelle (src/lib/sync-jobs.ts).
-- Procédure et contrôles : docs/ACTUALISATION.md, sections 3 et 5.1.
